# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/MMCM/MMCM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MMCM || ORIG_REF_NAME==MMCM} -quiet] -quiet
