# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.cache/wt [current_project]
set_property parent.project_path D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {C:/Users/Julian/AppData/Roaming/Xilinx/Vivado/2019.2/xhub/board_store} [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_output_repo d:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/bootloader.coe
read_verilog {
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/Acron_x32_constants.svh
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/FPU_constants.svh
}
set_property file_type "Verilog Header" [get_files D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/Acron_x32_constants.svh]
set_property file_type "Verilog Header" [get_files D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/FPU_constants.svh]
read_verilog -library xil_defaultlib -sv {
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/ALU.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/Acron_x32.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/FPU.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/control_unit.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/UART/fifo_stack.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/float_adder.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/float_arithmetic.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/float_comparator_comb.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/float_comparator_seq.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/float_divider.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/float_multiplier.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/float_sqrt.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/ftoi_converter.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/inst_decoder.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/int_divider.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/int_multiplier.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/itof_converter.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/jump_logic.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/leading_zero_counter_24.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/leading_zero_counter_32.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/leading_zero_counter_4.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/post_processing.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/pre_normalizer.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/register_file.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/rounding_logic.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/rshifter.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/rshifter_static.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/sign_modifier.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/FPU/splitter.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/Acron_x32/status_register.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/UART/uart.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/UART/uart_rx.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/UART/uart_tx.sv
  D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/new/FPGA_top.sv
}
read_ip -quiet D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/MMCM/MMCM.xci
set_property used_in_implementation false [get_files -all d:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/MMCM/MMCM_board.xdc]
set_property used_in_implementation false [get_files -all d:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/MMCM/MMCM.xdc]
set_property used_in_implementation false [get_files -all d:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/MMCM/MMCM_late.xdc]
set_property used_in_implementation false [get_files -all d:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/MMCM/MMCM_ooc.xdc]

read_ip -quiet D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all d:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

read_ip -quiet D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/ROM/ROM.xci
set_property used_in_implementation false [get_files -all d:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/sources_1/ip/ROM/ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FPGA_top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef -incremental_synth FPGA_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FPGA_top_utilization_synth.rpt -pb FPGA_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
