set_property SRC_FILE_INFO {cfile:D:/Benutzer/Documents/Vivado/Projects/Verilog/Acron_x32/Acron_x32.srcs/constrs_1/new/constraints.xdc rfile:../../../Acron_x32.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K17	IOSTANDARD LVCMOS33				} [get_ports { ref_clk				}]; #IO_L12P_T1_MRCC_35 Sch=sysclk
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K19	IOSTANDARD LVCMOS33				} [get_ports { mode_btn				}]; #IO_L10P_T1_AD11P_35 Sch=btn[2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y16	IOSTANDARD LVCMOS33				} [get_ports { reset_btn			}]; #IO_L7P_T1_34 Sch=btn[3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14	IOSTANDARD LVCMOS33				} [get_ports { rx_led				}]; #IO_L23P_T3_35 Sch=led[0]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M15	IOSTANDARD LVCMOS33				} [get_ports { tx_led				}]; #IO_L23N_T3_35 Sch=led[1]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G14	IOSTANDARD LVCMOS33				} [get_ports { halt_led				}]; #IO_0_35 Sch=led[2]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D18	IOSTANDARD LVCMOS33				} [get_ports { mode_led				}]; #IO_L3N_T0_DQS_AD1N_35 Sch=led[3]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V12	IOSTANDARD LVCMOS33				} [get_ports { rts					}]; #IO_L4P_T0_34 Sch=je[1]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W16	IOSTANDARD LVCMOS33	PULLUP true	} [get_ports { cts					}]; #IO_L18N_T2_34 Sch=je[2]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15	IOSTANDARD LVCMOS33				} [get_ports { tx					}]; #IO_25_35 Sch=je[3]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H15	IOSTANDARD LVCMOS33	PULLUP true	} [get_ports { rx					}]; #IO_L19P_T3_35 Sch=je[4]
